# Generated by Django 2.0.2 on 2018-10-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_urlfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='URLField',
            new_name='url',
        ),
    ]
